name: Test Opencast

on:
  pull_request:
    paths:
      - 'pom.xml'
      - 'modules/**'
      - 'docs/checkstyle/**'
      - 'docs/log4j/**'
      - 'assemblies/**'
  push:
    paths:
      - 'pom.xml'
      - 'modules/**'
      - 'docs/checkstyle/**'
      - 'docs/log4j/**'
      - 'assemblies/**'

jobs:
  build:
    strategy:
      matrix:
        java:
          - 8
          - 11
    name: build (java ${{ matrix.java }})
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: cache local maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: install dependencies
        run: |
          sudo apt update -q
          sudo apt install -y -q \
            bzip2 \
            ffmpeg \
            gzip \
            hunspell \
            hunspell-de-de \
            procps \
            sox \
            tar \
            tesseract-ocr \
            tesseract-ocr-deu \
            unzip

      - name: prepare build
        run: |
          sed -i 's/build --skipTests=${skipTests}/build --skipTests=true/' modules/admin-ui-frontend/pom.xml

      - name: build opencast
        run: |
          mvn --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
            clean install -Pnone
